version: '3.7'

services:
  web:
    build: 
        context: ./DARC
        dockerfile: Dockerfile
    command: gunicorn --graceful-timeout=7200 --timeout=7200 DARC.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/DARC/web/static
      - media_volume:/home/DARC/web/media
    ports:
      - 2007:8000
    env_file:
      - .env.prod

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/DARC/web/static
      - media_volume:/home/DARC/web/media
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  static_volume:
  media_volume: